const Categories = {
    SNACKS: 'SNACKS',
    BEVERAGES: 'BEVERAGES',
    HEALTHY_OPTIONS: 'HEALTHY_OPTIONS',
    MEALS_AND_SANDWICHES: 'MEALS_AND_SANDWICHES',
    DAIRY_PRODUCTS: 'DAIRY_PRODUCTS',
    BAKED_GOODS: 'BAKED_GOODS',
    FROZEN_TREATS: 'FROZEN_TREATS',
    NON_FOOD_ITEMS: 'NON_FOOD_ITEMS'
};